# Generated by Django 2.2.3 on 2019-07-22 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190722_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_avatar',
        ),
    ]
